file_read= open('codingal.txt','r')
print('File in read mode -')
print(file_read.read())
file_read.close()
file_write=open('codingal.txt','w')
file_write.write("File in write mode.....")
file_write.write("Hi! I am Penguin I am 10 yrs old.")
file_write.close()
file_append=open('codingal.txt','a')
file_append.write("\nFile in append mode....")
file_append.write("Hi! I am Penguin I am 10 yrs old.")
file_append.close()